# NumPy
- Numeric Python, uma biblioteca que fornece suporta para arrays e matrizes multidimensionais.

### NumPy - Arrays
- Criar arrays multidimensionais = np.array()
- Pode ter qualquer número de dimensões
- Usado para armazenar dados em matrizes e tensores

In [79]:
import numpy as np 
np.array([1,2,3,4])

array([1, 2, 3, 4])

### NumPy - Ndarrays
- Tensões são extensão de matrizes para mais de 2 dimensões
- Pode ter qualquer número de dimensões

In [80]:
matriz = np.array([[1.0,2],[3,4]])
matriz

array([[1., 2.],
       [3., 4.]])

In [81]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

- **dtype** é o atributo de um array que retorna o tipo de dados do elemento do array

In [82]:
print(matriz.dtype)
print(tensor.dtype)

float64
int64


- **shape** fornece o tamanho do array ao longo de cada dimensão

In [83]:
print(matriz.shape)
print(tensor.shape)

(2, 2)
(2, 2, 2)


### NumPy  - Criação de Ndarray

#### - Preenche a matriz com numero (1)

In [84]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### - Preenche a matriz com o número especificado

In [85]:
full = np.full((3,2),42)
full

array([[42, 42],
       [42, 42],
       [42, 42]])

#### - Preenche a matriz com o número (0)

In [86]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

### NumPy  - Valores aleatórios
 

- **numpy.random.rand**: gera valores aleatórios no intervalo [0, 1).

In [87]:
np.random.rand(2,3)

array([[0.09439468, 0.99854174, 0.98370215],
       [0.06954484, 0.66276897, 0.51692984]])

- **numpy.random.randint**: gera valores inteiros aleatórios em um intervalo especificado em uma forma especificada.

In [88]:
np.random.randint(0, 10, size=(2,3))

array([[7, 3, 7],
       [0, 1, 0]])

### NumPy - Indexação
- A indexação em um array NumPy é semelhante à indexação em uma lista ou vetor, com algumas diferenças.

In [89]:
a = np.array(([1, 2, 3], [4, 5, 6]))
print(a[0, 0]) #(linha 0, coluna 0)
print(a[0, 2]) #(linha 0, coluna 2)
print(a[-1, -1]) #(linha -1, coluna -1)

1
3
6


### NumPy - Operações

In [90]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("sum:          ",a.sum())
print("max:          ",a.max())
print("min:          ",a.min())
print("media:        ",a.mean())
print("std:          ",a.std())
print("var:          ",a.var())

sum:           21
max:           6
min:           1
media:         3.5
std:           1.707825127659933
var:           2.9166666666666665


# Pandas
- Biblioteca para análise e manipulação de dados.
- Estrutura de dados eficientes e alta performance
- Ferramentas para ler, escrever dados em vários formatos, .csv, excel, sql..
- Construída sobre a NumPy, podendo usar as operações do numpy no pandas (extensão da NumPy, recursos adicionais)

### Pandas - Series
- Series é uma estrutura de dados unidimensional, armazena diferentes tipos de dados
- Índice associado a cada valor

In [91]:
arr = np.array(range(10,20))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [92]:
import pandas as pd
pd.Series(arr)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

### Pandas - DataFrame
- DataFrame é uma estrutura de dados bidimensional, que armazena dados de diferentes tipos em diferentes colunas.
- Cada coluna ou linha pode ser relacionada a uma serie.
- DataFrame = junção de várias Series

In [93]:
mat = np.array([[1, 2, 3],[4, 5, 6]])
df = pd.DataFrame(mat)
df

0  1  2
0  1  2  3
1  4  5  6