# Exercícios com Numpy e Pandas

### 1. Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de dado do array.


In [4]:
import numpy as np 
arr = np.random.randint(0, 101, size=10)
arr


array([11, 28,  2,  5, 24, 60, 56, 73, 91, 68])

### 2. Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.


In [14]:
matriz = np.random.rand(5,5)
print(matriz)
print("max:          ",matriz.max())
print("min:          ",matriz.min())
print("media:        ",matriz.mean())


[[0.93145838 0.64395042 0.03405408 0.87430598 0.95775171]
 [0.02189287 0.56059106 0.92544408 0.40535621 0.32423497]
 [0.62314433 0.79326594 0.11791026 0.59136208 0.80328348]
 [0.09012543 0.15196626 0.87460369 0.24227064 0.32180316]
 [0.76051168 0.99116938 0.55967218 0.13483121 0.7846221 ]]
max:           0.9911693804732833
min:           0.0218928684243761
media:         0.5407832635423044


### 3. Crie um array com 10 elementos aleatórios no intervalo [0, 1). Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.


In [17]:
arr = np.random.rand(10)
print(arr)

new_arr = (arr * 10).astype(int)
print(new_arr)

[0.28656678 0.25178612 0.73960922 0.40725083 0.94703645 0.50496189
 0.01928441 0.34758728 0.31551873 0.3017322 ]
[2 2 7 4 9 5 0 3 3 3]


### 4. Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]. Substitua todos os elementos da segunda linha por -1.

In [18]:
arr = np.random.randint(0, 10, (3, 3))
arr[1, :] = -1 #indexação, acessa a segunda linha do array por 1, seleciona todos os elementos (`:`) da segunda linha (`1`) e atribuímos `-1`aos elementos

print(arr)


[[ 8  4  2]
 [-1 -1 -1]
 [ 7  3  6]]


### 6. Crie um DataFrame com as seguintes informações:
- Coluna "fruta": "Banana", "Maça", "Pera"
- Coluna "preco": 7.90, 10.20, 11.80
- Coluna "quantidade": 12, 3, 4


In [24]:
import pandas as pd
frutas = np.array([['fruta:', 'preço:', 'quantidade:'],['banana', 7.90, 12], ['maçã', 10.20, 3],['pêra', 11.80, 4]])
df = pd.DataFrame(frutas)
df

0       1            2
0  fruta:  preço:  quantidade:
1  banana     7.9           12
2    maçã    10.2            3
3    pêra    11.8            4

In [25]:
frutas = {
    "fruta": ["Banana", "Maçã", "Pera"],
    "preco": [7.90, 10.20, 11.80],
    "quantidade": [12, 3, 4]
}

df = pd.DataFrame(frutas)

df


fruta  preco  quantidade
0  Banana    7.9          12
1    Maçã   10.2           3
2    Pera   11.8           4